### ISSUE TITLE
Enable GitHub discussions?

### ISSUE THREAD

**Issue by viniciusferrao** [zauguin/i18n-cpp#2]
Hi @zauguin thanks for sharing this repo. 

Would you consider enabling Github discussions? I came across this repo and have some questions, but it's no issues. So to keep things clear would you mind?

Thank you for this library.

**Comment by zauguin** [comment]
I enabled discussions, but I'm currently very busy and are unlikely to be very responsive over the next two weeks...

**Comment by zauguin** [comment]
@viniciusferrao I have significantly more time now, so if you want to discuss something feel free to raise it.
